### ISSUE TITLE
Port all the tests!

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer_elements#1]
Community involvement on this one would be great, as there are north of 170 elements/behaviors total. To that end, and also for my own sanity, I am separating this out into a bunch of sub-tasks.

The goal is to just port all existing js tests, not to write tests of our own.
- [x] Iron Elements ([issue](https://github.com/dart-lang/polymer_elements/issues/2))
- [x] Gold Elements ([issue](https://github.com/dart-lang/polymer_elements/issues/3))
- [x] ~~Platinum Elements ([issue](https://github.com/dart-lang/polymer_elements/issues/4))~~
  - Ran into various issues and decided to remove these from the 1.0 roadmap at least for now. See https://github.com/dart-lang/polymer_elements/issues/12 for the issue to add them back.
- [x] Neon Elements ([issue](https://github.com/dart-lang/polymer_elements/issues/5))
- [x] Paper Elements ([issue](https://github.com/dart-lang/polymer_elements/issues/6))
- [x] Google Web Components ([issue](https://github.com/dart-lang/polymer_elements/issues/7))
- [x] Molecules ([issue](https://github.com/dart-lang/polymer_elements/issues/8))

**Comment by jakemac53** [comment]
There are a number of iron-\* tests in the repo which can be used as examples, and the `common.dart` file contains various helpers.

**Comment by jakemac53** [comment]
Also, fwiw any tests for behaviors should be skipped for now, as they are blocked on https://github.com/dart-lang/polymer-dart/issues/551

**Comment by jakemac53** [comment]
If any type signatures are wrong (discovering these is actually one of the main purposes of these tests), then proper annotations need to be added to the original js files under lib/src, and a pull request should be sent to the original repo as well.

The wrappers need to be regenerated once that is done, this can be accomplished by globally installing the `hydrolysis` package with npm (must install node/npm first), and then running `pub run custom_element_apigen:update polymer_elements_config.yaml`. Make sure you have version 1.15.3 or greater of the `hydrolysis` package, as the previous version doesn't pick up certain types of behaviors, which results in an error in the update script.

**Comment by jakemac53** [comment]
Ok I think we are done! Thanks a bunch @ErikGrimes and @vsheyanov for the help, that was a doozy :)

**Comment by vsheyanov** [comment]
Great news! Glad to help :)

**Comment by ErikGrimes** [comment]
Awesome!
