### ISSUE TITLE
Port the behaviors tests

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer_elements#13]
- [x] Iron behaviors ([issue](https://github.com/dart-lang/polymer_elements/issues/28))
- [x] ~~Neon behaviors ([issue](https://github.com/dart-lang/polymer_elements/issues/29))~~ No tests to port
- [x] Paper behaviors ([issue](https://github.com/dart-lang/polymer_elements/issues/30))

**Comment by jakemac53** [comment]
This is now unblocked in the [behaviors branch](https://github.com/dart-lang/polymer_elements/tree/behaviors) of the repo. This has not been merged with master for two reasons:
- It has a path dependency on `reflectable`, and a github dependency on the `behaviors` branch of polymer.
- The transformer in current version of reflectable does not quite fully work for our purposes yet (there are some unimplemented errors at runtime post-transformation). 

Once those issues are resolved we can merge the branch into master.

**Comment by jakemac53** [comment]
I also got the [neon_animated_pages_test](https://github.com/dart-lang/polymer_elements/blob/behaviors/test/neon_animated_pages_test.dart) working in this branch, just to confirm things are working as expected.

**Comment by jakemac53** [comment]
@ErikGrimes @vsheyanov If either of you would like to start porting behaviors tests this is ready (see notes above). You will need to locally clone the [reflectable](https://github.com/dart-lang/reflectable) package in a directory next to this repo in order to successfully run `pub get`.

**Comment by jakemac53** [comment]
- [ ] Iron behaviors
- [ ] Neon behaviors
- [ ] Paper behaviors

**Comment by jakemac53** [comment]
Ported the first one of these, so there is another example to work off of https://github.com/dart-lang/polymer_elements/commit/d71ea1e6ec06c75615f088b2855e60bffb7f27c5.

**Comment by jakemac53** [comment]
all done!
